language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 8.0
    
sudo: false

before_install:
    - composer validate 

install:
    - composer update --prefer-dist

before_script:
    - git submodule update --remote --recursive
    - cd cybersource-rest-samples-php
    - composer update --prefer-dist
    - cd ..
    - yes | cp -Rf vendor cybersource-rest-samples-php/
    - rm -Rf cybersource-rest-samples-php/vendor/cybersource/rest-client-php
    - cp -R lib cybersource-rest-samples-php/vendor/cybersource/rest-client-php/
    - ls cybersource-rest-samples-php/vendor/cybersource/rest-client-php/

script:
    - cd cybersource-rest-samples-php
    - bash sample_code_runner.sh