<?php
/**
 * AftFundingOptionsInitiator
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;

/**
 * AftFundingOptionsInitiator Class Doc Comment
 *
 * @category    Class
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AftFundingOptionsInitiator implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'aftFundingOptions_initiator';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'originatorInitiatedTransaction' => '\CyberSource\Model\AftFundingOptionsInitiatorOriginatorInitiatedTransaction',
        'type' => 'string',
        'storedCredentialUsed' => 'bool',
        'credentialStoredOnFile' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'originatorInitiatedTransaction' => null,
        'type' => null,
        'storedCredentialUsed' => null,
        'credentialStoredOnFile' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'originatorInitiatedTransaction' => 'originatorInitiatedTransaction',
        'type' => 'type',
        'storedCredentialUsed' => 'storedCredentialUsed',
        'credentialStoredOnFile' => 'credentialStoredOnFile'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'originatorInitiatedTransaction' => 'setOriginatorInitiatedTransaction',
        'type' => 'setType',
        'storedCredentialUsed' => 'setStoredCredentialUsed',
        'credentialStoredOnFile' => 'setCredentialStoredOnFile'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'originatorInitiatedTransaction' => 'getOriginatorInitiatedTransaction',
        'type' => 'getType',
        'storedCredentialUsed' => 'getStoredCredentialUsed',
        'credentialStoredOnFile' => 'getCredentialStoredOnFile'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['originatorInitiatedTransaction'] = isset($data['originatorInitiatedTransaction']) ? $data['originatorInitiatedTransaction'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['storedCredentialUsed'] = isset($data['storedCredentialUsed']) ? $data['storedCredentialUsed'] : null;
        $this->container['credentialStoredOnFile'] = isset($data['credentialStoredOnFile']) ? $data['credentialStoredOnFile'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets originatorInitiatedTransaction
     * @return \CyberSource\Model\AftFundingOptionsInitiatorOriginatorInitiatedTransaction
     */
    public function getOriginatorInitiatedTransaction()
    {
        return $this->container['originatorInitiatedTransaction'];
    }

    /**
     * Sets originatorInitiatedTransaction
     * @param \CyberSource\Model\AftFundingOptionsInitiatorOriginatorInitiatedTransaction $originatorInitiatedTransaction
     * @return $this
     */
    public function setOriginatorInitiatedTransaction($originatorInitiatedTransaction)
    {
        $this->container['originatorInitiatedTransaction'] = $originatorInitiatedTransaction;

        return $this;
    }

    /**
     * Gets type
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     * @param string $type This field indicates whether the transaction is a originator-initiated transaction or sender-initiated transaction.  Valid values: - `sender` - `originator`  Conditional field. If value in this field is `originator`, this field is mandatory for originator-initated transactions.
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets storedCredentialUsed
     * @return bool
     */
    public function getStoredCredentialUsed()
    {
        return $this->container['storedCredentialUsed'];
    }

    /**
     * Sets storedCredentialUsed
     * @param bool $storedCredentialUsed Indicates to an issuing bank whether an originator-initiated transaction came from a card that was already stored on file.  Possible values: - `True` = originator-initiated transaction came from a card that was already stored on file - `False` =  originator-initiated transaction came from a card that was not stored on file  Conditional for MITCOF transactions
     * @return $this
     */
    public function setStoredCredentialUsed($storedCredentialUsed)
    {
        $this->container['storedCredentialUsed'] = $storedCredentialUsed;

        return $this;
    }

    /**
     * Gets credentialStoredOnFile
     * @return bool
     */
    public function getCredentialStoredOnFile()
    {
        return $this->container['credentialStoredOnFile'];
    }

    /**
     * Sets credentialStoredOnFile
     * @param bool $credentialStoredOnFile Flag that indicates whether the transaction is the first originator-initiated transaction in a series, which means that the customer initiated the previous transaction.   Possible values: - `True`: First originator-initiated transaction - `False`: Not the first originator-initiated transaction  Conditional for MITCOF transactions
     * @return $this
     */
    public function setCredentialStoredOnFile($credentialStoredOnFile)
    {
        $this->container['credentialStoredOnFile'] = $credentialStoredOnFile;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}


