<?php
/**
 * InlineResponse20019GoogleMerchant
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;

/**
 * InlineResponse20019GoogleMerchant Class Doc Comment
 *
 * @category    Class
 * @description Google Merchant Center upload summary. Present only when Google Merchant integration is enabled for the merchant.
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20019GoogleMerchant implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'inline_response_200_19_google_merchant';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'status' => 'string',
        'ucpValidCount' => 'int',
        'ucpInvalidCount' => 'int',
        'googleEnabled' => 'bool',
        'products' => '\CyberSource\Model\InlineResponse20019GoogleMerchantProducts[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'status' => null,
        'ucpValidCount' => null,
        'ucpInvalidCount' => null,
        'googleEnabled' => null,
        'products' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'status' => 'status',
        'ucpValidCount' => 'ucp_valid_count',
        'ucpInvalidCount' => 'ucp_invalid_count',
        'googleEnabled' => 'google_enabled',
        'products' => 'products'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'status' => 'setStatus',
        'ucpValidCount' => 'setUcpValidCount',
        'ucpInvalidCount' => 'setUcpInvalidCount',
        'googleEnabled' => 'setGoogleEnabled',
        'products' => 'setProducts'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'status' => 'getStatus',
        'ucpValidCount' => 'getUcpValidCount',
        'ucpInvalidCount' => 'getUcpInvalidCount',
        'googleEnabled' => 'getGoogleEnabled',
        'products' => 'getProducts'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['ucpValidCount'] = isset($data['ucpValidCount']) ? $data['ucpValidCount'] : null;
        $this->container['ucpInvalidCount'] = isset($data['ucpInvalidCount']) ? $data['ucpInvalidCount'] : null;
        $this->container['googleEnabled'] = isset($data['googleEnabled']) ? $data['googleEnabled'] : null;
        $this->container['products'] = isset($data['products']) ? $data['products'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status Upload outcome status: - `TRIGGERED` — async upload dispatched; check Google Merchant Center for results - `FAILED` — all products failed UCP validation; nothing sent to Google - `DISABLED` — Google Merchant integration is disabled for this merchant - `COMPLETED` — synchronous validate-and-upload completed   Possible values: - TRIGGERED - FAILED - DISABLED - COMPLETED
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets ucpValidCount
     * @return int
     */
    public function getUcpValidCount()
    {
        return $this->container['ucpValidCount'];
    }

    /**
     * Sets ucpValidCount
     * @param int $ucpValidCount Number of products that passed UCP validation and were queued for upload.
     * @return $this
     */
    public function setUcpValidCount($ucpValidCount)
    {
        $this->container['ucpValidCount'] = $ucpValidCount;

        return $this;
    }

    /**
     * Gets ucpInvalidCount
     * @return int
     */
    public function getUcpInvalidCount()
    {
        return $this->container['ucpInvalidCount'];
    }

    /**
     * Sets ucpInvalidCount
     * @param int $ucpInvalidCount Number of products that failed UCP validation and were not sent to Google.
     * @return $this
     */
    public function setUcpInvalidCount($ucpInvalidCount)
    {
        $this->container['ucpInvalidCount'] = $ucpInvalidCount;

        return $this;
    }

    /**
     * Gets googleEnabled
     * @return bool
     */
    public function getGoogleEnabled()
    {
        return $this->container['googleEnabled'];
    }

    /**
     * Sets googleEnabled
     * @param bool $googleEnabled Whether Google Merchant integration is enabled for this merchant.
     * @return $this
     */
    public function setGoogleEnabled($googleEnabled)
    {
        $this->container['googleEnabled'] = $googleEnabled;

        return $this;
    }

    /**
     * Gets products
     * @return \CyberSource\Model\InlineResponse20019GoogleMerchantProducts[]
     */
    public function getProducts()
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     * @param \CyberSource\Model\InlineResponse20019GoogleMerchantProducts[] $products Per-product UCP validation and upload results. Populated when at least one product was saved successfully. Null when all products failed ACG-level validation.
     * @return $this
     */
    public function setProducts($products)
    {
        $this->container['products'] = $products;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}


