<?php
/**
 * Ptsv2paymentsProcessorInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;

/**
 * Ptsv2paymentsProcessorInformation Class Doc Comment
 *
 * @category    Class
 * @description Processor Information
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsProcessorInformation implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ptsv2payments_processorInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'preApprovalToken' => 'string',
        'authorizationOptions' => '\CyberSource\Model\Ptsv2paymentsProcessorInformationAuthorizationOptions',
        'reversal' => '\CyberSource\Model\Ptsv2paymentsProcessorInformationReversal',
        'network' => '\CyberSource\Model\Ptsv2paymentsProcessorInformationReversalNetwork',
        'authApprovalToken' => 'string',
        'supplementaryTransactionData' => 'string',
        'responseSourceCode' => 'string',
        'cedpVerifiedIndicator' => 'string',
        'feeProgramIndicator' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'preApprovalToken' => null,
        'authorizationOptions' => null,
        'reversal' => null,
        'network' => null,
        'authApprovalToken' => null,
        'supplementaryTransactionData' => null,
        'responseSourceCode' => null,
        'cedpVerifiedIndicator' => null,
        'feeProgramIndicator' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'preApprovalToken' => 'preApprovalToken',
        'authorizationOptions' => 'authorizationOptions',
        'reversal' => 'reversal',
        'network' => 'network',
        'authApprovalToken' => 'authApprovalToken',
        'supplementaryTransactionData' => 'supplementaryTransactionData',
        'responseSourceCode' => 'responseSourceCode',
        'cedpVerifiedIndicator' => 'cedpVerifiedIndicator',
        'feeProgramIndicator' => 'feeProgramIndicator'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'preApprovalToken' => 'setPreApprovalToken',
        'authorizationOptions' => 'setAuthorizationOptions',
        'reversal' => 'setReversal',
        'network' => 'setNetwork',
        'authApprovalToken' => 'setAuthApprovalToken',
        'supplementaryTransactionData' => 'setSupplementaryTransactionData',
        'responseSourceCode' => 'setResponseSourceCode',
        'cedpVerifiedIndicator' => 'setCedpVerifiedIndicator',
        'feeProgramIndicator' => 'setFeeProgramIndicator'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'preApprovalToken' => 'getPreApprovalToken',
        'authorizationOptions' => 'getAuthorizationOptions',
        'reversal' => 'getReversal',
        'network' => 'getNetwork',
        'authApprovalToken' => 'getAuthApprovalToken',
        'supplementaryTransactionData' => 'getSupplementaryTransactionData',
        'responseSourceCode' => 'getResponseSourceCode',
        'cedpVerifiedIndicator' => 'getCedpVerifiedIndicator',
        'feeProgramIndicator' => 'getFeeProgramIndicator'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['preApprovalToken'] = isset($data['preApprovalToken']) ? $data['preApprovalToken'] : null;
        $this->container['authorizationOptions'] = isset($data['authorizationOptions']) ? $data['authorizationOptions'] : null;
        $this->container['reversal'] = isset($data['reversal']) ? $data['reversal'] : null;
        $this->container['network'] = isset($data['network']) ? $data['network'] : null;
        $this->container['authApprovalToken'] = isset($data['authApprovalToken']) ? $data['authApprovalToken'] : null;
        $this->container['supplementaryTransactionData'] = isset($data['supplementaryTransactionData']) ? $data['supplementaryTransactionData'] : null;
        $this->container['responseSourceCode'] = isset($data['responseSourceCode']) ? $data['responseSourceCode'] : null;
        $this->container['cedpVerifiedIndicator'] = isset($data['cedpVerifiedIndicator']) ? $data['cedpVerifiedIndicator'] : null;
        $this->container['feeProgramIndicator'] = isset($data['feeProgramIndicator']) ? $data['feeProgramIndicator'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets preApprovalToken
     * @return string
     */
    public function getPreApprovalToken()
    {
        return $this->container['preApprovalToken'];
    }

    /**
     * Sets preApprovalToken
     * @param string $preApprovalToken Token received in original session service.
     * @return $this
     */
    public function setPreApprovalToken($preApprovalToken)
    {
        $this->container['preApprovalToken'] = $preApprovalToken;

        return $this;
    }

    /**
     * Gets authorizationOptions
     * @return \CyberSource\Model\Ptsv2paymentsProcessorInformationAuthorizationOptions
     */
    public function getAuthorizationOptions()
    {
        return $this->container['authorizationOptions'];
    }

    /**
     * Sets authorizationOptions
     * @param \CyberSource\Model\Ptsv2paymentsProcessorInformationAuthorizationOptions $authorizationOptions
     * @return $this
     */
    public function setAuthorizationOptions($authorizationOptions)
    {
        $this->container['authorizationOptions'] = $authorizationOptions;

        return $this;
    }

    /**
     * Gets reversal
     * @return \CyberSource\Model\Ptsv2paymentsProcessorInformationReversal
     */
    public function getReversal()
    {
        return $this->container['reversal'];
    }

    /**
     * Sets reversal
     * @param \CyberSource\Model\Ptsv2paymentsProcessorInformationReversal $reversal
     * @return $this
     */
    public function setReversal($reversal)
    {
        $this->container['reversal'] = $reversal;

        return $this;
    }

    /**
     * Gets network
     * @return \CyberSource\Model\Ptsv2paymentsProcessorInformationReversalNetwork
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     * @param \CyberSource\Model\Ptsv2paymentsProcessorInformationReversalNetwork $network
     * @return $this
     */
    public function setNetwork($network)
    {
        $this->container['network'] = $network;

        return $this;
    }

    /**
     * Gets authApprovalToken
     * @return string
     */
    public function getAuthApprovalToken()
    {
        return $this->container['authApprovalToken'];
    }

    /**
     * Sets authApprovalToken
     * @param string $authApprovalToken Interoperability Token received by merchant for Authorization API. Field for merchant to send Klarna Advantage Plus authorization approval token for Auth API call.
     * @return $this
     */
    public function setAuthApprovalToken($authApprovalToken)
    {
        $this->container['authApprovalToken'] = $authApprovalToken;

        return $this;
    }

    /**
     * Gets supplementaryTransactionData
     * @return string
     */
    public function getSupplementaryTransactionData()
    {
        return $this->container['supplementaryTransactionData'];
    }

    /**
     * Sets supplementaryTransactionData
     * @param string $supplementaryTransactionData Supplementary transaction data for Klarna Advantage Plus. Fields to capture Interoperability Data from Merchant and transfer to Klarna for Authorization/Sale/Re-Auth/Capture APIs.
     * @return $this
     */
    public function setSupplementaryTransactionData($supplementaryTransactionData)
    {
        $this->container['supplementaryTransactionData'] = $supplementaryTransactionData;

        return $this;
    }

    /**
     * Gets responseSourceCode
     * @return string
     */
    public function getResponseSourceCode()
    {
        return $this->container['responseSourceCode'];
    }

    /**
     * Sets responseSourceCode
     * @param string $responseSourceCode Field contains the response source code that identifies the source.
     * @return $this
     */
    public function setResponseSourceCode($responseSourceCode)
    {
        $this->container['responseSourceCode'] = $responseSourceCode;

        return $this;
    }

    /**
     * Gets cedpVerifiedIndicator
     * @return string
     */
    public function getCedpVerifiedIndicator()
    {
        return $this->container['cedpVerifiedIndicator'];
    }

    /**
     * Sets cedpVerifiedIndicator
     * @param string $cedpVerifiedIndicator Merchant Commercial Enhanced Data Program (CEDP) verified indicator for capture/bill requests.  This field is used when the client is doing authorization with a different gateway and capture/settlement with CyberSource.  This field flows in ISO field 34, DSID 02 tag DA, in AN, EBCDIC format.  Possible values: - `Y`: Merchant CEDP verified  #### Used by **Capture Request** Request field for force capture/bill support when auth is done with a different gateway.
     * @return $this
     */
    public function setCedpVerifiedIndicator($cedpVerifiedIndicator)
    {
        $this->container['cedpVerifiedIndicator'] = $cedpVerifiedIndicator;

        return $this;
    }

    /**
     * Gets feeProgramIndicator
     * @return string
     */
    public function getFeeProgramIndicator()
    {
        return $this->container['feeProgramIndicator'];
    }

    /**
     * Sets feeProgramIndicator
     * @param string $feeProgramIndicator Interchange reimbursement fee program indicator (FPI), which is used when assessing the fee applied to a cross-border or domestic Asia Pacific financial transaction. Acquirers and issues retain and return the FPI value in chargeback and representments.
     * @return $this
     */
    public function setFeeProgramIndicator($feeProgramIndicator)
    {
        $this->container['feeProgramIndicator'] = $feeProgramIndicator;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}


