<?php
/**
 * Ptsv2paymentsProcessingInformationJapanPaymentOptions
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;

/**
 * Ptsv2paymentsProcessingInformationJapanPaymentOptions Class Doc Comment
 *
 * @category    Class
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsProcessingInformationJapanPaymentOptions implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ptsv2payments_processingInformation_japanPaymentOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'paymentMethod' => 'string',
        'bonuses' => 'string',
        'bonusMonth' => 'string',
        'secondBonusMonth' => 'string',
        'bonusAmount' => 'string',
        'secondBonusAmount' => 'string',
        'preapprovalType' => 'string',
        'installments' => 'string',
        'terminalId' => 'string',
        'firstBillingMonth' => 'string',
        'businessName' => 'string',
        'businessNameKatakana' => 'string',
        'jis2TrackData' => 'string',
        'businessNameAlphaNumeric' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'paymentMethod' => null,
        'bonuses' => null,
        'bonusMonth' => null,
        'secondBonusMonth' => null,
        'bonusAmount' => null,
        'secondBonusAmount' => null,
        'preapprovalType' => null,
        'installments' => null,
        'terminalId' => null,
        'firstBillingMonth' => null,
        'businessName' => null,
        'businessNameKatakana' => null,
        'jis2TrackData' => null,
        'businessNameAlphaNumeric' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'paymentMethod' => 'paymentMethod',
        'bonuses' => 'bonuses',
        'bonusMonth' => 'bonusMonth',
        'secondBonusMonth' => 'secondBonusMonth',
        'bonusAmount' => 'bonusAmount',
        'secondBonusAmount' => 'secondBonusAmount',
        'preapprovalType' => 'preapprovalType',
        'installments' => 'installments',
        'terminalId' => 'terminalId',
        'firstBillingMonth' => 'firstBillingMonth',
        'businessName' => 'businessName',
        'businessNameKatakana' => 'businessNameKatakana',
        'jis2TrackData' => 'jis2TrackData',
        'businessNameAlphaNumeric' => 'businessNameAlphaNumeric'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'paymentMethod' => 'setPaymentMethod',
        'bonuses' => 'setBonuses',
        'bonusMonth' => 'setBonusMonth',
        'secondBonusMonth' => 'setSecondBonusMonth',
        'bonusAmount' => 'setBonusAmount',
        'secondBonusAmount' => 'setSecondBonusAmount',
        'preapprovalType' => 'setPreapprovalType',
        'installments' => 'setInstallments',
        'terminalId' => 'setTerminalId',
        'firstBillingMonth' => 'setFirstBillingMonth',
        'businessName' => 'setBusinessName',
        'businessNameKatakana' => 'setBusinessNameKatakana',
        'jis2TrackData' => 'setJis2TrackData',
        'businessNameAlphaNumeric' => 'setBusinessNameAlphaNumeric'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'paymentMethod' => 'getPaymentMethod',
        'bonuses' => 'getBonuses',
        'bonusMonth' => 'getBonusMonth',
        'secondBonusMonth' => 'getSecondBonusMonth',
        'bonusAmount' => 'getBonusAmount',
        'secondBonusAmount' => 'getSecondBonusAmount',
        'preapprovalType' => 'getPreapprovalType',
        'installments' => 'getInstallments',
        'terminalId' => 'getTerminalId',
        'firstBillingMonth' => 'getFirstBillingMonth',
        'businessName' => 'getBusinessName',
        'businessNameKatakana' => 'getBusinessNameKatakana',
        'jis2TrackData' => 'getJis2TrackData',
        'businessNameAlphaNumeric' => 'getBusinessNameAlphaNumeric'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['paymentMethod'] = isset($data['paymentMethod']) ? $data['paymentMethod'] : null;
        $this->container['bonuses'] = isset($data['bonuses']) ? $data['bonuses'] : null;
        $this->container['bonusMonth'] = isset($data['bonusMonth']) ? $data['bonusMonth'] : null;
        $this->container['secondBonusMonth'] = isset($data['secondBonusMonth']) ? $data['secondBonusMonth'] : null;
        $this->container['bonusAmount'] = isset($data['bonusAmount']) ? $data['bonusAmount'] : null;
        $this->container['secondBonusAmount'] = isset($data['secondBonusAmount']) ? $data['secondBonusAmount'] : null;
        $this->container['preapprovalType'] = isset($data['preapprovalType']) ? $data['preapprovalType'] : null;
        $this->container['installments'] = isset($data['installments']) ? $data['installments'] : null;
        $this->container['terminalId'] = isset($data['terminalId']) ? $data['terminalId'] : null;
        $this->container['firstBillingMonth'] = isset($data['firstBillingMonth']) ? $data['firstBillingMonth'] : null;
        $this->container['businessName'] = isset($data['businessName']) ? $data['businessName'] : null;
        $this->container['businessNameKatakana'] = isset($data['businessNameKatakana']) ? $data['businessNameKatakana'] : null;
        $this->container['jis2TrackData'] = isset($data['jis2TrackData']) ? $data['jis2TrackData'] : null;
        $this->container['businessNameAlphaNumeric'] = isset($data['businessNameAlphaNumeric']) ? $data['businessNameAlphaNumeric'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets paymentMethod
     * @return string
     */
    public function getPaymentMethod()
    {
        return $this->container['paymentMethod'];
    }

    /**
     * Sets paymentMethod
     * @param string $paymentMethod This value is a 2-digit code indicating the payment method. Use Payment Method Code value that applies to the tranasction. - 10 (One-time payment) - 21, 22, 23, 24  (Bonus(one-time)payment) - 61 (Installment payment) - 31, 32, 33, 34  (Integrated (Bonus + Installment)payment) - 80 (Revolving payment)
     * @return $this
     */
    public function setPaymentMethod($paymentMethod)
    {

        $this->container['paymentMethod'] = $paymentMethod;

        return $this;
    }

    /**
     * Gets bonuses
     * @return string
     */
    public function getBonuses()
    {
        return $this->container['bonuses'];
    }

    /**
     * Sets bonuses
     * @param string $bonuses This value is a 2-digit code indicating the Number of Bonuses. Valid value from 1 to 6.
     * @return $this
     */
    public function setBonuses($bonuses)
    {

        $this->container['bonuses'] = $bonuses;

        return $this;
    }

    /**
     * Gets bonusMonth
     * @return string
     */
    public function getBonusMonth()
    {
        return $this->container['bonusMonth'];
    }

    /**
     * Sets bonusMonth
     * @param string $bonusMonth This value is a 2-digit code indicating the first bonus month. Valid value from 1 to 12.
     * @return $this
     */
    public function setBonusMonth($bonusMonth)
    {

        $this->container['bonusMonth'] = $bonusMonth;

        return $this;
    }

    /**
     * Gets secondBonusMonth
     * @return string
     */
    public function getSecondBonusMonth()
    {
        return $this->container['secondBonusMonth'];
    }

    /**
     * Sets secondBonusMonth
     * @param string $secondBonusMonth This value is a 2-digit code indicating the second bonus month. Valid value from 1 to 12.
     * @return $this
     */
    public function setSecondBonusMonth($secondBonusMonth)
    {

        $this->container['secondBonusMonth'] = $secondBonusMonth;

        return $this;
    }

    /**
     * Gets bonusAmount
     * @return string
     */
    public function getBonusAmount()
    {
        return $this->container['bonusAmount'];
    }

    /**
     * Sets bonusAmount
     * @param string $bonusAmount This value contains the bonus amount of the first month. Maximum value without decimal 99999999.
     * @return $this
     */
    public function setBonusAmount($bonusAmount)
    {

        $this->container['bonusAmount'] = $bonusAmount;

        return $this;
    }

    /**
     * Gets secondBonusAmount
     * @return string
     */
    public function getSecondBonusAmount()
    {
        return $this->container['secondBonusAmount'];
    }

    /**
     * Sets secondBonusAmount
     * @param string $secondBonusAmount This value contains the bonus amount of the second month. Maximum value without decimal 99999999.
     * @return $this
     */
    public function setSecondBonusAmount($secondBonusAmount)
    {

        $this->container['secondBonusAmount'] = $secondBonusAmount;

        return $this;
    }

    /**
     * Gets preapprovalType
     * @return string
     */
    public function getPreapprovalType()
    {
        return $this->container['preapprovalType'];
    }

    /**
     * Sets preapprovalType
     * @param string $preapprovalType This will contain the details of the kind of transaction that has been processe. Used only for Japan. Possible Values: - 0 = Normal (authorization with amount and clearing/settlement; data capture or paper draft) - 1 = Negative card authorization (authorization-only with 0 or 1 amount) - 2 = Reservation of authorization (authorization-only with amount) - 3 = Cancel transaction - 4 = Merchant-initiated reversal/refund transactions - 5 = Cancel reservation of authorization - 6 = Post authorization
     * @return $this
     */
    public function setPreapprovalType($preapprovalType)
    {

        $this->container['preapprovalType'] = $preapprovalType;

        return $this;
    }

    /**
     * Gets installments
     * @return string
     */
    public function getInstallments()
    {
        return $this->container['installments'];
    }

    /**
     * Sets installments
     * @param string $installments Number of Installments.
     * @return $this
     */
    public function setInstallments($installments)
    {
        $this->container['installments'] = $installments;

        return $this;
    }

    /**
     * Gets terminalId
     * @return string
     */
    public function getTerminalId()
    {
        return $this->container['terminalId'];
    }

    /**
     * Sets terminalId
     * @param string $terminalId Unique Japan Credit Card Association (JCCA) terminal identifier.  The difference between this field and the `pointOfSaleInformation.terminalID` field is that you can define `pointOfSaleInformation.terminalID`, but `processingInformation.japanPaymentOptions.terminalId` is defined by the JCCA and is used only in Japan.  This field is supported only on CyberSource through VisaNet and JCN Gateway.  Optional field.
     * @return $this
     */
    public function setTerminalId($terminalId)
    {

        $this->container['terminalId'] = $terminalId;

        return $this;
    }

    /**
     * Gets firstBillingMonth
     * @return string
     */
    public function getFirstBillingMonth()
    {
        return $this->container['firstBillingMonth'];
    }

    /**
     * Sets firstBillingMonth
     * @param string $firstBillingMonth Billing month in MM format.
     * @return $this
     */
    public function setFirstBillingMonth($firstBillingMonth)
    {

        $this->container['firstBillingMonth'] = $firstBillingMonth;

        return $this;
    }

    /**
     * Gets businessName
     * @return string
     */
    public function getBusinessName()
    {
        return $this->container['businessName'];
    }

    /**
     * Sets businessName
     * @param string $businessName Business name in Japanese characters. This field is supported only on JCN Gateway and for the Sumitomo Mitsui Card Co. acquirer on CyberSource through VisaNet.
     * @return $this
     */
    public function setBusinessName($businessName)
    {

        $this->container['businessName'] = $businessName;

        return $this;
    }

    /**
     * Gets businessNameKatakana
     * @return string
     */
    public function getBusinessNameKatakana()
    {
        return $this->container['businessNameKatakana'];
    }

    /**
     * Sets businessNameKatakana
     * @param string $businessNameKatakana Business name in Katakana characters. This field is supported only on JCN Gateway and for the Sumitomo Mitsui Card Co. acquirer on CyberSource through VisaNet.
     * @return $this
     */
    public function setBusinessNameKatakana($businessNameKatakana)
    {

        $this->container['businessNameKatakana'] = $businessNameKatakana;

        return $this;
    }

    /**
     * Gets jis2TrackData
     * @return string
     */
    public function getJis2TrackData()
    {
        return $this->container['jis2TrackData'];
    }

    /**
     * Sets jis2TrackData
     * @param string $jis2TrackData Japanese Industrial Standard Type 2 (JIS2) track data from the front of the card.  This field is supported only on CyberSource through VisaNet and JCN Gateway.  Optional field.
     * @return $this
     */
    public function setJis2TrackData($jis2TrackData)
    {

        $this->container['jis2TrackData'] = $jis2TrackData;

        return $this;
    }

    /**
     * Gets businessNameAlphaNumeric
     * @return string
     */
    public function getBusinessNameAlphaNumeric()
    {
        return $this->container['businessNameAlphaNumeric'];
    }

    /**
     * Sets businessNameAlphaNumeric
     * @param string $businessNameAlphaNumeric Business name in alphanumeric characters. This field is supported only on JCN Gateway and for the Sumitomo Mitsui Card Co. acquirer on CyberSource through VisaNet.
     * @return $this
     */
    public function setBusinessNameAlphaNumeric($businessNameAlphaNumeric)
    {

        $this->container['businessNameAlphaNumeric'] = $businessNameAlphaNumeric;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}


