<?php
/**
 * UnifiedriskPaymentBankAccountBranchAddress
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;

/**
 * UnifiedriskPaymentBankAccountBranchAddress Class Doc Comment
 *
 * @category    Class
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnifiedriskPaymentBankAccountBranchAddress implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'unifiedrisk_payment_bankAccount_branchAddress';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'addressLine1' => 'string',
        'addressLine2' => 'string',
        'addressLine3' => 'string',
        'addressType' => 'string',
        'country' => 'string',
        'administrativeArea' => 'string',
        'fullAddress' => 'string',
        'latitude' => 'float',
        'longitude' => 'float',
        'postalCode' => 'string',
        'locality' => 'string',
        'countrySubDivision' => 'string',
        'townName' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'addressLine1' => null,
        'addressLine2' => null,
        'addressLine3' => null,
        'addressType' => null,
        'country' => null,
        'administrativeArea' => null,
        'fullAddress' => null,
        'latitude' => null,
        'longitude' => null,
        'postalCode' => null,
        'locality' => null,
        'countrySubDivision' => null,
        'townName' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'addressLine1' => 'addressLine1',
        'addressLine2' => 'addressLine2',
        'addressLine3' => 'addressLine3',
        'addressType' => 'addressType',
        'country' => 'country',
        'administrativeArea' => 'administrativeArea',
        'fullAddress' => 'fullAddress',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'postalCode' => 'postalCode',
        'locality' => 'locality',
        'countrySubDivision' => 'countrySubDivision',
        'townName' => 'townName'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'addressLine1' => 'setAddressLine1',
        'addressLine2' => 'setAddressLine2',
        'addressLine3' => 'setAddressLine3',
        'addressType' => 'setAddressType',
        'country' => 'setCountry',
        'administrativeArea' => 'setAdministrativeArea',
        'fullAddress' => 'setFullAddress',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'postalCode' => 'setPostalCode',
        'locality' => 'setLocality',
        'countrySubDivision' => 'setCountrySubDivision',
        'townName' => 'setTownName'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'addressLine1' => 'getAddressLine1',
        'addressLine2' => 'getAddressLine2',
        'addressLine3' => 'getAddressLine3',
        'addressType' => 'getAddressType',
        'country' => 'getCountry',
        'administrativeArea' => 'getAdministrativeArea',
        'fullAddress' => 'getFullAddress',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'postalCode' => 'getPostalCode',
        'locality' => 'getLocality',
        'countrySubDivision' => 'getCountrySubDivision',
        'townName' => 'getTownName'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['addressLine1'] = isset($data['addressLine1']) ? $data['addressLine1'] : null;
        $this->container['addressLine2'] = isset($data['addressLine2']) ? $data['addressLine2'] : null;
        $this->container['addressLine3'] = isset($data['addressLine3']) ? $data['addressLine3'] : null;
        $this->container['addressType'] = isset($data['addressType']) ? $data['addressType'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['administrativeArea'] = isset($data['administrativeArea']) ? $data['administrativeArea'] : null;
        $this->container['fullAddress'] = isset($data['fullAddress']) ? $data['fullAddress'] : null;
        $this->container['latitude'] = isset($data['latitude']) ? $data['latitude'] : null;
        $this->container['longitude'] = isset($data['longitude']) ? $data['longitude'] : null;
        $this->container['postalCode'] = isset($data['postalCode']) ? $data['postalCode'] : null;
        $this->container['locality'] = isset($data['locality']) ? $data['locality'] : null;
        $this->container['countrySubDivision'] = isset($data['countrySubDivision']) ? $data['countrySubDivision'] : null;
        $this->container['townName'] = isset($data['townName']) ? $data['townName'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets addressLine1
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->container['addressLine1'];
    }

    /**
     * Sets addressLine1
     * @param string $addressLine1 Address line 1
     * @return $this
     */
    public function setAddressLine1($addressLine1)
    {
        $this->container['addressLine1'] = $addressLine1;

        return $this;
    }

    /**
     * Gets addressLine2
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->container['addressLine2'];
    }

    /**
     * Sets addressLine2
     * @param string $addressLine2 Address line 2
     * @return $this
     */
    public function setAddressLine2($addressLine2)
    {
        $this->container['addressLine2'] = $addressLine2;

        return $this;
    }

    /**
     * Gets addressLine3
     * @return string
     */
    public function getAddressLine3()
    {
        return $this->container['addressLine3'];
    }

    /**
     * Sets addressLine3
     * @param string $addressLine3 Address line 3
     * @return $this
     */
    public function setAddressLine3($addressLine3)
    {
        $this->container['addressLine3'] = $addressLine3;

        return $this;
    }

    /**
     * Gets addressType
     * @return string
     */
    public function getAddressType()
    {
        return $this->container['addressType'];
    }

    /**
     * Sets addressType
     * @param string $addressType Identifies the nature of the postal address. Examples are \"Home\" or \"Work\".
     * @return $this
     */
    public function setAddressType($addressType)
    {
        $this->container['addressType'] = $addressType;

        return $this;
    }

    /**
     * Gets country
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     * @param string $country Nation with its own government, country code in ISO 3166 apha-3 format
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets administrativeArea
     * @return string
     */
    public function getAdministrativeArea()
    {
        return $this->container['administrativeArea'];
    }

    /**
     * Sets administrativeArea
     * @param string $administrativeArea Identifies a subdivision of a country such as state, region, county
     * @return $this
     */
    public function setAdministrativeArea($administrativeArea)
    {
        $this->container['administrativeArea'] = $administrativeArea;

        return $this;
    }

    /**
     * Gets fullAddress
     * @return string
     */
    public function getFullAddress()
    {
        return $this->container['fullAddress'];
    }

    /**
     * Sets fullAddress
     * @param string $fullAddress Full string containing all submitted address components.
     * @return $this
     */
    public function setFullAddress($fullAddress)
    {
        $this->container['fullAddress'] = $fullAddress;

        return $this;
    }

    /**
     * Gets latitude
     * @return float
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     * @param float $latitude Latitude of the address
     * @return $this
     */
    public function setLatitude($latitude)
    {
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     * @return float
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     * @param float $longitude Longitude of the address
     * @return $this
     */
    public function setLongitude($longitude)
    {
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets postalCode
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postalCode'];
    }

    /**
     * Sets postalCode
     * @param string $postalCode Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail
     * @return $this
     */
    public function setPostalCode($postalCode)
    {
        $this->container['postalCode'] = $postalCode;

        return $this;
    }

    /**
     * Gets locality
     * @return string
     */
    public function getLocality()
    {
        return $this->container['locality'];
    }

    /**
     * Sets locality
     * @param string $locality Name of a built-up area, with defined boundaries, and a local government.
     * @return $this
     */
    public function setLocality($locality)
    {
        $this->container['locality'] = $locality;

        return $this;
    }

    /**
     * Gets countrySubDivision
     * @return string
     */
    public function getCountrySubDivision()
    {
        return $this->container['countrySubDivision'];
    }

    /**
     * Sets countrySubDivision
     * @param string $countrySubDivision ISO 3166-2 subdivision code for the bank branch address state or province (e.g., US-NY, GB-ENG). Used for branch-level regulatory and geographic risk analysis
     * @return $this
     */
    public function setCountrySubDivision($countrySubDivision)
    {
        $this->container['countrySubDivision'] = $countrySubDivision;

        return $this;
    }

    /**
     * Gets townName
     * @return string
     */
    public function getTownName()
    {
        return $this->container['townName'];
    }

    /**
     * Sets townName
     * @param string $townName Town or city name of the bank branch used for geographic proximity analysis and branch-level risk profiling
     * @return $this
     */
    public function setTownName($townName)
    {
        $this->container['townName'] = $townName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}


