<?php
/**
 * UnifiedriskPaymentBatch
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CyberSource\Model;

use \ArrayAccess;

/**
 * UnifiedriskPaymentBatch Class Doc Comment
 *
 * @category    Class
 * @description Container for ACH/BACS batch payment metadata including file control fields, batch counts, and integrity checksums
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnifiedriskPaymentBatch implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'unifiedrisk_payment_batch';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'batchNumber' => 'string',
        'categoryPurposeDescription' => 'string',
        'endOfBatchIndicator' => 'bool',
        'endOfFileIndicator' => 'bool',
        'entryDetailRecNum' => 'float',
        'fileIdModifier' => 'string',
        'numberOfAddendaRecords' => 'float',
        'serviceClassCode' => 'string',
        'totalBatchCountInFile' => 'float',
        'totalBatchEntries' => 'float',
        'totalEntryCountInFile' => 'float',
        'totalEntryHash' => 'float',
        'totalTransitCountInFile' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'batchNumber' => null,
        'categoryPurposeDescription' => null,
        'endOfBatchIndicator' => null,
        'endOfFileIndicator' => null,
        'entryDetailRecNum' => null,
        'fileIdModifier' => null,
        'numberOfAddendaRecords' => null,
        'serviceClassCode' => null,
        'totalBatchCountInFile' => null,
        'totalBatchEntries' => null,
        'totalEntryCountInFile' => null,
        'totalEntryHash' => null,
        'totalTransitCountInFile' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'batchNumber' => 'batchNumber',
        'categoryPurposeDescription' => 'categoryPurposeDescription',
        'endOfBatchIndicator' => 'endOfBatchIndicator',
        'endOfFileIndicator' => 'endOfFileIndicator',
        'entryDetailRecNum' => 'entryDetailRecNum',
        'fileIdModifier' => 'fileIdModifier',
        'numberOfAddendaRecords' => 'numberOfAddendaRecords',
        'serviceClassCode' => 'serviceClassCode',
        'totalBatchCountInFile' => 'totalBatchCountInFile',
        'totalBatchEntries' => 'totalBatchEntries',
        'totalEntryCountInFile' => 'totalEntryCountInFile',
        'totalEntryHash' => 'totalEntryHash',
        'totalTransitCountInFile' => 'totalTransitCountInFile'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'batchNumber' => 'setBatchNumber',
        'categoryPurposeDescription' => 'setCategoryPurposeDescription',
        'endOfBatchIndicator' => 'setEndOfBatchIndicator',
        'endOfFileIndicator' => 'setEndOfFileIndicator',
        'entryDetailRecNum' => 'setEntryDetailRecNum',
        'fileIdModifier' => 'setFileIdModifier',
        'numberOfAddendaRecords' => 'setNumberOfAddendaRecords',
        'serviceClassCode' => 'setServiceClassCode',
        'totalBatchCountInFile' => 'setTotalBatchCountInFile',
        'totalBatchEntries' => 'setTotalBatchEntries',
        'totalEntryCountInFile' => 'setTotalEntryCountInFile',
        'totalEntryHash' => 'setTotalEntryHash',
        'totalTransitCountInFile' => 'setTotalTransitCountInFile'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'batchNumber' => 'getBatchNumber',
        'categoryPurposeDescription' => 'getCategoryPurposeDescription',
        'endOfBatchIndicator' => 'getEndOfBatchIndicator',
        'endOfFileIndicator' => 'getEndOfFileIndicator',
        'entryDetailRecNum' => 'getEntryDetailRecNum',
        'fileIdModifier' => 'getFileIdModifier',
        'numberOfAddendaRecords' => 'getNumberOfAddendaRecords',
        'serviceClassCode' => 'getServiceClassCode',
        'totalBatchCountInFile' => 'getTotalBatchCountInFile',
        'totalBatchEntries' => 'getTotalBatchEntries',
        'totalEntryCountInFile' => 'getTotalEntryCountInFile',
        'totalEntryHash' => 'getTotalEntryHash',
        'totalTransitCountInFile' => 'getTotalTransitCountInFile'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['batchNumber'] = isset($data['batchNumber']) ? $data['batchNumber'] : null;
        $this->container['categoryPurposeDescription'] = isset($data['categoryPurposeDescription']) ? $data['categoryPurposeDescription'] : null;
        $this->container['endOfBatchIndicator'] = isset($data['endOfBatchIndicator']) ? $data['endOfBatchIndicator'] : null;
        $this->container['endOfFileIndicator'] = isset($data['endOfFileIndicator']) ? $data['endOfFileIndicator'] : null;
        $this->container['entryDetailRecNum'] = isset($data['entryDetailRecNum']) ? $data['entryDetailRecNum'] : null;
        $this->container['fileIdModifier'] = isset($data['fileIdModifier']) ? $data['fileIdModifier'] : null;
        $this->container['numberOfAddendaRecords'] = isset($data['numberOfAddendaRecords']) ? $data['numberOfAddendaRecords'] : null;
        $this->container['serviceClassCode'] = isset($data['serviceClassCode']) ? $data['serviceClassCode'] : null;
        $this->container['totalBatchCountInFile'] = isset($data['totalBatchCountInFile']) ? $data['totalBatchCountInFile'] : null;
        $this->container['totalBatchEntries'] = isset($data['totalBatchEntries']) ? $data['totalBatchEntries'] : null;
        $this->container['totalEntryCountInFile'] = isset($data['totalEntryCountInFile']) ? $data['totalEntryCountInFile'] : null;
        $this->container['totalEntryHash'] = isset($data['totalEntryHash']) ? $data['totalEntryHash'] : null;
        $this->container['totalTransitCountInFile'] = isset($data['totalTransitCountInFile']) ? $data['totalTransitCountInFile'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets batchNumber
     * @return string
     */
    public function getBatchNumber()
    {
        return $this->container['batchNumber'];
    }

    /**
     * Sets batchNumber
     * @param string $batchNumber Unique sequential identifier for this batch within the batch file, used for tracking and reconciliation of ACH or BACS batch submissions
     * @return $this
     */
    public function setBatchNumber($batchNumber)
    {
        $this->container['batchNumber'] = $batchNumber;

        return $this;
    }

    /**
     * Gets categoryPurposeDescription
     * @return string
     */
    public function getCategoryPurposeDescription()
    {
        return $this->container['categoryPurposeDescription'];
    }

    /**
     * Sets categoryPurposeDescription
     * @param string $categoryPurposeDescription Human-readable description of the business purpose for the batch (e.g., \"Payroll\", \"Vendor Payments\"). Corresponds to the ISO 20022 CategoryPurpose code
     * @return $this
     */
    public function setCategoryPurposeDescription($categoryPurposeDescription)
    {
        $this->container['categoryPurposeDescription'] = $categoryPurposeDescription;

        return $this;
    }

    /**
     * Gets endOfBatchIndicator
     * @return bool
     */
    public function getEndOfBatchIndicator()
    {
        return $this->container['endOfBatchIndicator'];
    }

    /**
     * Sets endOfBatchIndicator
     * @param bool $endOfBatchIndicator Indicates this entry is the last record in the current batch. Used to signal batch boundary during file processing
     * @return $this
     */
    public function setEndOfBatchIndicator($endOfBatchIndicator)
    {
        $this->container['endOfBatchIndicator'] = $endOfBatchIndicator;

        return $this;
    }

    /**
     * Gets endOfFileIndicator
     * @return bool
     */
    public function getEndOfFileIndicator()
    {
        return $this->container['endOfFileIndicator'];
    }

    /**
     * Sets endOfFileIndicator
     * @param bool $endOfFileIndicator Indicates this entry is the last record in the entire batch file. Used to trigger final file validation and processing
     * @return $this
     */
    public function setEndOfFileIndicator($endOfFileIndicator)
    {
        $this->container['endOfFileIndicator'] = $endOfFileIndicator;

        return $this;
    }

    /**
     * Gets entryDetailRecNum
     * @return float
     */
    public function getEntryDetailRecNum()
    {
        return $this->container['entryDetailRecNum'];
    }

    /**
     * Sets entryDetailRecNum
     * @param float $entryDetailRecNum Sequential record number of the entry detail record within the batch, used for file integrity checks and record-level reconciliation
     * @return $this
     */
    public function setEntryDetailRecNum($entryDetailRecNum)
    {
        $this->container['entryDetailRecNum'] = $entryDetailRecNum;

        return $this;
    }

    /**
     * Gets fileIdModifier
     * @return string
     */
    public function getFileIdModifier()
    {
        return $this->container['fileIdModifier'];
    }

    /**
     * Sets fileIdModifier
     * @param string $fileIdModifier Single character modifier (A-Z) used to distinguish multiple batch files submitted on the same day for the same originator
     * @return $this
     */
    public function setFileIdModifier($fileIdModifier)
    {
        $this->container['fileIdModifier'] = $fileIdModifier;

        return $this;
    }

    /**
     * Gets numberOfAddendaRecords
     * @return float
     */
    public function getNumberOfAddendaRecords()
    {
        return $this->container['numberOfAddendaRecords'];
    }

    /**
     * Sets numberOfAddendaRecords
     * @param float $numberOfAddendaRecords Count of addenda records associated with this batch entry, used for validating batch completeness during file processing
     * @return $this
     */
    public function setNumberOfAddendaRecords($numberOfAddendaRecords)
    {
        $this->container['numberOfAddendaRecords'] = $numberOfAddendaRecords;

        return $this;
    }

    /**
     * Gets serviceClassCode
     * @return string
     */
    public function getServiceClassCode()
    {
        return $this->container['serviceClassCode'];
    }

    /**
     * Sets serviceClassCode
     * @param string $serviceClassCode ACH service class code indicating the type of entries in the batch. Values - \"200\" (mixed), \"220\" (credits only), \"225\" (debits only), \"280\" (automated accounting)
     * @return $this
     */
    public function setServiceClassCode($serviceClassCode)
    {
        $this->container['serviceClassCode'] = $serviceClassCode;

        return $this;
    }

    /**
     * Gets totalBatchCountInFile
     * @return float
     */
    public function getTotalBatchCountInFile()
    {
        return $this->container['totalBatchCountInFile'];
    }

    /**
     * Sets totalBatchCountInFile
     * @param float $totalBatchCountInFile Total number of batches contained in this file, used for file-level control validation and balancing
     * @return $this
     */
    public function setTotalBatchCountInFile($totalBatchCountInFile)
    {
        $this->container['totalBatchCountInFile'] = $totalBatchCountInFile;

        return $this;
    }

    /**
     * Gets totalBatchEntries
     * @return float
     */
    public function getTotalBatchEntries()
    {
        return $this->container['totalBatchEntries'];
    }

    /**
     * Sets totalBatchEntries
     * @param float $totalBatchEntries Total count of entry detail records within this batch, used for batch-level balancing and reconciliation
     * @return $this
     */
    public function setTotalBatchEntries($totalBatchEntries)
    {
        $this->container['totalBatchEntries'] = $totalBatchEntries;

        return $this;
    }

    /**
     * Gets totalEntryCountInFile
     * @return float
     */
    public function getTotalEntryCountInFile()
    {
        return $this->container['totalEntryCountInFile'];
    }

    /**
     * Sets totalEntryCountInFile
     * @param float $totalEntryCountInFile Total count of all entry detail records across all batches in the file, used for file-level reconciliation
     * @return $this
     */
    public function setTotalEntryCountInFile($totalEntryCountInFile)
    {
        $this->container['totalEntryCountInFile'] = $totalEntryCountInFile;

        return $this;
    }

    /**
     * Gets totalEntryHash
     * @return float
     */
    public function getTotalEntryHash()
    {
        return $this->container['totalEntryHash'];
    }

    /**
     * Sets totalEntryHash
     * @param float $totalEntryHash Arithmetic sum of all routing transit numbers within the batch/file, used as a checksum for routing number validation
     * @return $this
     */
    public function setTotalEntryHash($totalEntryHash)
    {
        $this->container['totalEntryHash'] = $totalEntryHash;

        return $this;
    }

    /**
     * Gets totalTransitCountInFile
     * @return float
     */
    public function getTotalTransitCountInFile()
    {
        return $this->container['totalTransitCountInFile'];
    }

    /**
     * Sets totalTransitCountInFile
     * @param float $totalTransitCountInFile Total count of distinct routing transit numbers in the file, used for clearing house validation and routing verification
     * @return $this
     */
    public function setTotalTransitCountInFile($totalTransitCountInFile)
    {
        $this->container['totalTransitCountInFile'] = $totalTransitCountInFile;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}


