<?php
/**
 * InlineResponse2002BuyerInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Flex API
 *
 * Simple PAN tokenization service
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InlineResponse2002BuyerInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2002BuyerInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002BuyerInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002BuyerInformation"
     */
    public function testInlineResponse2002BuyerInformation()
    {
    }

    /**
     * Test attribute "merchantCustomerId"
     */
    public function testPropertyMerchantCustomerId()
    {
    }

    /**
     * Test attribute "dateOfBirth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "vatRegistrationNumber"
     */
    public function testPropertyVatRegistrationNumber()
    {
    }

    /**
     * Test attribute "personalIdentification"
     */
    public function testPropertyPersonalIdentification()
    {
    }

    /**
     * Test attribute "taxId"
     */
    public function testPropertyTaxId()
    {
    }
}
