<?php
/**
 * InlineResponse2016SetupsValueAddedServicesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * InlineResponse2016SetupsValueAddedServicesTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2016SetupsValueAddedServices
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2016SetupsValueAddedServicesTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2016SetupsValueAddedServices"
     */
    public function testInlineResponse2016SetupsValueAddedServices()
    {
    }

    /**
     * Test attribute "reporting"
     */
    public function testPropertyReporting()
    {
    }

    /**
     * Test attribute "transactionSearch"
     */
    public function testPropertyTransactionSearch()
    {
    }

    /**
     * Test attribute "bankAccountValidation"
     */
    public function testPropertyBankAccountValidation()
    {
    }

    /**
     * Test attribute "flexapi"
     */
    public function testPropertyFlexapi()
    {
    }

    /**
     * Test attribute "webhooks"
     */
    public function testPropertyWebhooks()
    {
    }

    /**
     * Test attribute "smarterRetry"
     */
    public function testPropertySmarterRetry()
    {
    }
}
