<?php
/**
 * PtsV2PaymentsPost201Response1ProcessorInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PtsV2PaymentsPost201Response1ProcessorInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsPost201Response1ProcessorInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsPost201Response1ProcessorInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsPost201Response1ProcessorInformation"
     */
    public function testPtsV2PaymentsPost201Response1ProcessorInformation()
    {
    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "tradeNumber"
     */
    public function testPropertyTradeNumber()
    {
    }

    /**
     * Test attribute "rawResponse"
     */
    public function testPropertyRawResponse()
    {
    }

    /**
     * Test attribute "rawResponseLocal"
     */
    public function testPropertyRawResponseLocal()
    {
    }

    /**
     * Test attribute "responseDetails"
     */
    public function testPropertyResponseDetails()
    {
    }

    /**
     * Test attribute "responseCode"
     */
    public function testPropertyResponseCode()
    {
    }

    /**
     * Test attribute "sellerProtection"
     */
    public function testPropertySellerProtection()
    {
    }

    /**
     * Test attribute "paymentUrl"
     */
    public function testPropertyPaymentUrl()
    {
    }

    /**
     * Test attribute "avs"
     */
    public function testPropertyAvs()
    {
    }
}
