<?php
/**
 * Ptsv2paymentsidcapturesProcessingInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ptsv2paymentsidcapturesProcessingInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2paymentsidcapturesProcessingInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsidcapturesProcessingInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ptsv2paymentsidcapturesProcessingInformation"
     */
    public function testPtsv2paymentsidcapturesProcessingInformation()
    {
    }

    /**
     * Test attribute "paymentSolution"
     */
    public function testPropertyPaymentSolution()
    {
    }

    /**
     * Test attribute "reconciliationId"
     */
    public function testPropertyReconciliationId()
    {
    }

    /**
     * Test attribute "linkId"
     */
    public function testPropertyLinkId()
    {
    }

    /**
     * Test attribute "reportGroup"
     */
    public function testPropertyReportGroup()
    {
    }

    /**
     * Test attribute "visaCheckoutId"
     */
    public function testPropertyVisaCheckoutId()
    {
    }

    /**
     * Test attribute "purchaseLevel"
     */
    public function testPropertyPurchaseLevel()
    {
    }

    /**
     * Test attribute "industryDataType"
     */
    public function testPropertyIndustryDataType()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "authorizationOptions"
     */
    public function testPropertyAuthorizationOptions()
    {
    }

    /**
     * Test attribute "captureOptions"
     */
    public function testPropertyCaptureOptions()
    {
    }

    /**
     * Test attribute "loanOptions"
     */
    public function testPropertyLoanOptions()
    {
    }

    /**
     * Test attribute "payByPointsIndicator"
     */
    public function testPropertyPayByPointsIndicator()
    {
    }
}
