<?php
/**
 * Ptsv2paymentsConsumerAuthenticationInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Ptsv2paymentsConsumerAuthenticationInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2paymentsConsumerAuthenticationInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsConsumerAuthenticationInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Ptsv2paymentsConsumerAuthenticationInformation"
     */
    public function testPtsv2paymentsConsumerAuthenticationInformation()
    {
    }

    /**
     * Test attribute "cavv"
     */
    public function testPropertyCavv()
    {
    }

    /**
     * Test attribute "cavvAlgorithm"
     */
    public function testPropertyCavvAlgorithm()
    {
    }

    /**
     * Test attribute "eciRaw"
     */
    public function testPropertyEciRaw()
    {
    }

    /**
     * Test attribute "paresStatus"
     */
    public function testPropertyParesStatus()
    {
    }

    /**
     * Test attribute "veresEnrolled"
     */
    public function testPropertyVeresEnrolled()
    {
    }

    /**
     * Test attribute "xid"
     */
    public function testPropertyXid()
    {
    }

    /**
     * Test attribute "ucafAuthenticationData"
     */
    public function testPropertyUcafAuthenticationData()
    {
    }

    /**
     * Test attribute "ucafCollectionIndicator"
     */
    public function testPropertyUcafCollectionIndicator()
    {
    }
}
