<?php
/**
 * PtsV2PaymentsPost201Response2ProcessorInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * PtsV2PaymentsPost201Response2ProcessorInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsPost201Response2ProcessorInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsPost201Response2ProcessorInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PtsV2PaymentsPost201Response2ProcessorInformation"
     */
    public function testPtsV2PaymentsPost201Response2ProcessorInformation()
    {
    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "paymentUrl"
     */
    public function testPropertyPaymentUrl()
    {
    }

    /**
     * Test attribute "responseDetails"
     */
    public function testPropertyResponseDetails()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "responseCode"
     */
    public function testPropertyResponseCode()
    {
    }
}
