<?php
/**
 * Riskv1decisionsPaymentInformationTokenizedCardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Riskv1decisionsPaymentInformationTokenizedCardTest Class Doc Comment
 *
 * @category    Class */
// * @description Use this object to submit a payment network token instead of card-based values.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Riskv1decisionsPaymentInformationTokenizedCardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Riskv1decisionsPaymentInformationTokenizedCard"
     */
    public function testRiskv1decisionsPaymentInformationTokenizedCard()
    {
    }

    /**
     * Test attribute "transactionType"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "expirationMonth"
     */
    public function testPropertyExpirationMonth()
    {
    }

    /**
     * Test attribute "expirationYear"
     */
    public function testPropertyExpirationYear()
    {
    }
}
