<?php
/**
 * Riskv1authenticationsConsumerAuthenticationInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * Riskv1authenticationsConsumerAuthenticationInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Riskv1authenticationsConsumerAuthenticationInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Riskv1authenticationsConsumerAuthenticationInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Riskv1authenticationsConsumerAuthenticationInformation"
     */
    public function testRiskv1authenticationsConsumerAuthenticationInformation()
    {
    }

    /**
     * Test attribute "alternateAuthenticationData"
     */
    public function testPropertyAlternateAuthenticationData()
    {
    }

    /**
     * Test attribute "alternateAuthenticationDate"
     */
    public function testPropertyAlternateAuthenticationDate()
    {
    }

    /**
     * Test attribute "alternateAuthenticationMethod"
     */
    public function testPropertyAlternateAuthenticationMethod()
    {
    }

    /**
     * Test attribute "authenticationTransactionId"
     */
    public function testPropertyAuthenticationTransactionId()
    {
    }

    /**
     * Test attribute "challengeCode"
     */
    public function testPropertyChallengeCode()
    {
    }

    /**
     * Test attribute "customerCardAlias"
     */
    public function testPropertyCustomerCardAlias()
    {
    }

    /**
     * Test attribute "defaultCard"
     */
    public function testPropertyDefaultCard()
    {
    }

    /**
     * Test attribute "installmentTotalCount"
     */
    public function testPropertyInstallmentTotalCount()
    {
    }

    /**
     * Test attribute "marketingOptIn"
     */
    public function testPropertyMarketingOptIn()
    {
    }

    /**
     * Test attribute "marketingSource"
     */
    public function testPropertyMarketingSource()
    {
    }

    /**
     * Test attribute "mcc"
     */
    public function testPropertyMcc()
    {
    }

    /**
     * Test attribute "messageCategory"
     */
    public function testPropertyMessageCategory()
    {
    }

    /**
     * Test attribute "npaCode"
     */
    public function testPropertyNpaCode()
    {
    }

    /**
     * Test attribute "overridePaymentMethod"
     */
    public function testPropertyOverridePaymentMethod()
    {
    }

    /**
     * Test attribute "productCode"
     */
    public function testPropertyProductCode()
    {
    }

    /**
     * Test attribute "requestorId"
     */
    public function testPropertyRequestorId()
    {
    }

    /**
     * Test attribute "requestorName"
     */
    public function testPropertyRequestorName()
    {
    }

    /**
     * Test attribute "referenceId"
     */
    public function testPropertyReferenceId()
    {
    }

    /**
     * Test attribute "transactionMode"
     */
    public function testPropertyTransactionMode()
    {
    }
}
