<?php
/**
 * TssV2TransactionsGet200ResponseProcessorInformationElectronicVerificationResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * TssV2TransactionsGet200ResponseProcessorInformationElectronicVerificationResultsTest Class Doc Comment
 *
 * @category    Class */
// * @description TssV2TransactionsGet200ResponseProcessorInformationElectronicVerificationResults
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TssV2TransactionsGet200ResponseProcessorInformationElectronicVerificationResultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TssV2TransactionsGet200ResponseProcessorInformationElectronicVerificationResults"
     */
    public function testTssV2TransactionsGet200ResponseProcessorInformationElectronicVerificationResults()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "emailRaw"
     */
    public function testPropertyEmailRaw()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "nameRaw"
     */
    public function testPropertyNameRaw()
    {
    }

    /**
     * Test attribute "phoneNumber"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "phoneNumberRaw"
     */
    public function testPropertyPhoneNumberRaw()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "streetRaw"
     */
    public function testPropertyStreetRaw()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "postalCodeRaw"
     */
    public function testPropertyPostalCodeRaw()
    {
    }
}
