<?php
/**
 * TssV2TransactionsGet200ResponseApplicationInformationApplicationsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * TssV2TransactionsGet200ResponseApplicationInformationApplicationsTest Class Doc Comment
 *
 * @category    Class */
// * @description TssV2TransactionsGet200ResponseApplicationInformationApplications
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TssV2TransactionsGet200ResponseApplicationInformationApplicationsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TssV2TransactionsGet200ResponseApplicationInformationApplications"
     */
    public function testTssV2TransactionsGet200ResponseApplicationInformationApplications()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "reasonCode"
     */
    public function testPropertyReasonCode()
    {
    }

    /**
     * Test attribute "rCode"
     */
    public function testPropertyRCode()
    {
    }

    /**
     * Test attribute "rFlag"
     */
    public function testPropertyRFlag()
    {
    }

    /**
     * Test attribute "reconciliationId"
     */
    public function testPropertyReconciliationId()
    {
    }

    /**
     * Test attribute "rMessage"
     */
    public function testPropertyRMessage()
    {
    }

    /**
     * Test attribute "returnCode"
     */
    public function testPropertyReturnCode()
    {
    }
}
