<?php
/**
 * UnderwritingConfigurationOrganizationInformationBusinessInformationDirectorInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * UnderwritingConfigurationOrganizationInformationBusinessInformationDirectorInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description UnderwritingConfigurationOrganizationInformationBusinessInformationDirectorInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnderwritingConfigurationOrganizationInformationBusinessInformationDirectorInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UnderwritingConfigurationOrganizationInformationBusinessInformationDirectorInformation"
     */
    public function testUnderwritingConfigurationOrganizationInformationBusinessInformationDirectorInformation()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "middleName"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "birthDate"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "phoneNumber"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
    }

    /**
     * Test attribute "nationalId"
     */
    public function testPropertyNationalId()
    {
    }

    /**
     * Test attribute "idCountry"
     */
    public function testPropertyIdCountry()
    {
    }

    /**
     * Test attribute "passportNumber"
     */
    public function testPropertyPassportNumber()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }
}
