<?php
/**
 * UnifiedriskCustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * UnifiedriskCustomerTest Class Doc Comment
 *
 * @category    Class */
// * @description Customer identity, profile information, account history, and personal identification documents
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnifiedriskCustomerTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UnifiedriskCustomer"
     */
    public function testUnifiedriskCustomer()
    {
    }

    /**
     * Test attribute "merchantCustomerId"
     */
    public function testPropertyMerchantCustomerId()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "hashedPassword"
     */
    public function testPropertyHashedPassword()
    {
    }

    /**
     * Test attribute "personalIdentification"
     */
    public function testPropertyPersonalIdentification()
    {
    }

    /**
     * Test attribute "enrollmentDate"
     */
    public function testPropertyEnrollmentDate()
    {
    }

    /**
     * Test attribute "flags"
     */
    public function testPropertyFlags()
    {
    }

    /**
     * Test attribute "customerId"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "agentType"
     */
    public function testPropertyAgentType()
    {
    }

    /**
     * Test attribute "agentId"
     */
    public function testPropertyAgentId()
    {
    }

    /**
     * Test attribute "agentConfidenceScore"
     */
    public function testPropertyAgentConfidenceScore()
    {
    }

    /**
     * Test attribute "agentDelegationScope"
     */
    public function testPropertyAgentDelegationScope()
    {
    }

    /**
     * Test attribute "agentInteractionTimestamp"
     */
    public function testPropertyAgentInteractionTimestamp()
    {
    }

    /**
     * Test attribute "isBusiness"
     */
    public function testPropertyIsBusiness()
    {
    }

    /**
     * Test attribute "businessName"
     */
    public function testPropertyBusinessName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }
}
