<?php
/**
 * VpriRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CyberSource;

/**
 * VpriRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description Unified risk assessment request with action-based routing
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VpriRequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VpriRequest"
     */
    public function testVpriRequest()
    {
    }

    /**
     * Test attribute "actions"
     */
    public function testPropertyActions()
    {
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
    }

    /**
     * Test attribute "transaction"
     */
    public function testPropertyTransaction()
    {
    }

    /**
     * Test attribute "requestId"
     */
    public function testPropertyRequestId()
    {
    }

    /**
     * Test attribute "eventTime"
     */
    public function testPropertyEventTime()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
    }

    /**
     * Test attribute "requestComments"
     */
    public function testPropertyRequestComments()
    {
    }

    /**
     * Test attribute "schemaVersion"
     */
    public function testPropertySchemaVersion()
    {
    }

    /**
     * Test attribute "partner"
     */
    public function testPropertyPartner()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "riskAssessment"
     */
    public function testPropertyRiskAssessment()
    {
    }

    /**
     * Test attribute "travel"
     */
    public function testPropertyTravel()
    {
    }

    /**
     * Test attribute "merchant"
     */
    public function testPropertyMerchant()
    {
    }

    /**
     * Test attribute "acquirer"
     */
    public function testPropertyAcquirer()
    {
    }

    /**
     * Test attribute "device"
     */
    public function testPropertyDevice()
    {
    }

    /**
     * Test attribute "session"
     */
    public function testPropertySession()
    {
    }

    /**
     * Test attribute "supplementaryData"
     */
    public function testPropertySupplementaryData()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "authentication"
     */
    public function testPropertyAuthentication()
    {
    }

    /**
     * Test attribute "authorization"
     */
    public function testPropertyAuthorization()
    {
    }

    /**
     * Test attribute "browser"
     */
    public function testPropertyBrowser()
    {
    }

    /**
     * Test attribute "initiatingParty"
     */
    public function testPropertyInitiatingParty()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "thirdPartyRisk"
     */
    public function testPropertyThirdPartyRisk()
    {
    }
}
