name: PHP BUILDS
on:
  push:
  pull_request: 
  workflow_dispatch:
env:
  CLIENT_FOLDER: 'cybersource-rest-client-php'
  SAMPLE_FOLDER: 'cybersource-rest-samples-php'
jobs:
    workflow-job:
        defaults:
            run:
              shell: bash
        strategy:
            fail-fast: false
            matrix:
              operating-system: [ubuntu-latest,macos-latest,windows-latest]
              php-ver: ['8.0','8.1','8.2','8.3','8.4']  
        run-on: ${{matrix.operating-system}}
        steps:
            - name: Creating separate folders for checkout repos
              run: |
                rm -rf $CLIENT_FOLDER
                rm -rf $SAMPLE_FOLDER
                mkdir $CLIENT_FOLDER $SAMPLE_FOLDER
            - name: Checkout cybersource-rest-client-php repo
              uses: actions/checkout@v4
              with:
                path: ${{env.CLIENT_FOLDER}}
            - name: Checkout cybersource-rest-samples-php repo
              uses: actions/checkout@v4
              with:
                repository: 'CyberSource/${{env.SAMPLE_FOLDER}}'
                ref: 'testing-ref'
                path: ${{env.SAMPLE_FOLDER}}
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                node-version: ${{matrix.php-ver}}
                extensions: mbstring, curl, openssl, zip
            - name: Building the projects and running the Test Cases
              run: |
                php --version

            